apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app   : phpmyadmin
    owner : rulrike
spec:
  # Replicas - это свойство объекта Spec развертывания, которое определяет, сколько подов мы хотим запустить.
  replicas: 1
  # Новые поды становятся готовыми или доступными (по крайней мере, через MinReadySeconds).
  minReadySeconds: 15
  # Тип указывает стратегию, используемую в этом развертывании при переходе от текущей версии к следующей.
  # Стратегия RollingUpdate обеспечивает нулевое время простоя при развертывании.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # После завершения работы одного модуля у нас все еще будет работать один модуль, таким образом сохраняя доступность нашего приложения
      maxUnavailable: 1
      # Определяет максимальное количество модулей, добавляемых к развертыванию
      maxSurge: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        # Image - это образ контейнера, который мы хотим запустить в этом поде.
        image: phpmyadmin_image
        # Отключаем возможность подтягивать image с dockerhub 
        imagePullPolicy: Never
        # Порт контейнера: порт, который прослушивает контейнер. Это всего лишь индикатор для читателя (отключение порта не ограничивает доступ).
        ports:
        - containerPort: 5000
---

apiVersion: v1
# Kind: указывает тип ресурса Kubernetes, который мы хотим создать.
kind: Service
metadata:
  # Имя: определяет имя ресурса.
  name: phpmyadmin-service
  # Чтобы запросить назначение из определенного пула, прописываем эту строчку 
  annotations:
        metallb.universe.tf/allow-shared-ip: services
# Spec - это объект, определяющий желаемое состояние ресурса.
spec:
  type: LoadBalancer
  # Selector: объект, содержащий свойства для выбора модулей.
  selector:
    app: phpmyadmin
  ports:
    - name: http-port-for-phpmyadmin
      protocol: TCP
      port: 5000
      targetPort: 5000