apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app   : ftps
    owner : rulrike
spec:
  # Replicas - это свойство объекта Spec развертывания, которое определяет, сколько подов мы хотим запустить.
  replicas: 1
  # Новые поды становятся готовыми или доступными (по крайней мере, через MinReadySeconds).
  minReadySeconds: 15
  # Тип указывает стратегию, используемую в этом развертывании при переходе от текущей версии к следующей.
  # Стратегия RollingUpdate обеспечивает нулевое время простоя при развертывании.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # После завершения работы одного модуля у нас все еще будет работать один модуль, таким образом сохраняя доступность нашего приложения
      maxUnavailable: 1
      # Определяет максимальное количество модулей, добавляемых к развертыванию
      maxSurge: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        # Image - это образ контейнера, который мы хотим запустить в этом поде.
        image: ftps_image
        # Отключаем возможность подтягивать image с dockerhub 
        imagePullPolicy: Never
        # Порт контейнера: порт, который прослушивает контейнер. Это всего лишь индикатор для читателя (отключение порта не ограничивает доступ).
        ports:
        - containerPort: 21
        - containerPort: 21000
---
apiVersion: v1
# Kind: указывает тип ресурса Kubernetes, который мы хотим создать.
kind: Service
metadata:
  # Имя: определяет имя ресурса.
  name: ftps-service
  labels:
    app  : mysql
    owner: rulrike
  # Чтобы запросить назначение из определенного пула, прописываем эту строчку 
  annotations:
        metallb.universe.tf/allow-shared-ip: services
# Spec - это объект, определяющий желаемое состояние ресурса.
spec:
  # Selector: объект, содержащий свойства для выбора модулей.
  selector:
    app: ftps
  # Тип спецификации, мы выбираем LoadBalancer, чтобы получить айпи адрес к которому можно будет подключиться извне
  type: LoadBalancer
  # Port: указывает порт, через который служба получает запросы.
  # TargetPort: порт, на который перенаправляются входящие запросы.
  # Protocol определяет связь.
  ports:
    - name: https
      protocol: TCP
      port: 21
      targetPort: 21
      # TCP гарантирует доставку пакетов данных через порт 21000 в том же порядке, в котором они были отправлены.
    - name: port-for-data
      protocol: TCP
      port: 21000
      targetPort: 21000